//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolDBEntities1 : DbContext
    {
        public SchoolDBEntities1()
            : base("name=SchoolDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Lesson> Lesson { get; set; }
        public virtual DbSet<Mark> Mark { get; set; }
        public virtual DbSet<Palor> Palor { get; set; }
        public virtual DbSet<Pupil> Pupil { get; set; }
        public virtual DbSet<ReportCard> ReportCard { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
    }
}
